# This file was auto-generated by the flowing compiler (compiler_version=0.1.3), from: root.fya
# Do not edit by hand (the py_hash gate rejects external modifications); to hand-edit, promote it to a handwritten subclass.
from flowing import Agent, PENDING, Parsable


class RootAgent(Agent):
    source_file = '<repo-root>/dev-docs/tutorial-en/6-1/root.fya'
    description = Parsable('Interfaces demo assistant: minimal Q&A.')
    system_prompt = Parsable('You are a concise English assistant.')
    model_tag = 'default'
