# 6-1 semantic assertions: target the recorded transcript and project files;
# no real provider is called.
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8")


def test_project_files_complete():
    for name in ("main.py", "root.fya", "providers.yaml",
                 "models.yaml", "model-tags.yaml", "notes/scratch.fya"):
        assert (ROOT / name).is_file(), f"missing project file: {name}"


def test_transcripts_present():
    p = ROOT / "demo_output.txt"
    assert p.is_file() and p.stat().st_size > 0


def test_smoke_test_subcommand():
    out = read("demo_output.txt")
    first = out.split("$ echo")[0]
    assert "uv run flowing test ." in first
    assert "exit=0" in first, "test: smoke boot (launch + snapshot assertion + shutdown)"


def test_repl_debug_eval():
    out = read("demo_output.txt")
    seg = out.split("repl-debug")[1].split("compile")[0]
    assert ">>>agent-main" in seg, "repl-debug /eval evaluates in the Agent context"


def test_compile_subcommand():
    out = read("demo_output.txt")
    seg = out.split("compile")[1]
    assert "exit=0" in seg
    assert (ROOT / "notes" / "scratch.py").is_file(), "compile writes the .py artifact"
    py = read("notes/scratch.py")
    assert "generated by the flowing compiler" in py
    assert "class ScratchAgent(Agent)" in py
